---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.2"
  origin:
    repo: "https://github.com/atomist-rugs/travis-editors.git"
    branch: "fb5fab9406ad30c0be90cb8272a8bb22fd8a3242"
    sha: "fb5fab9"
  parameters:
    - "repo_slug": "atomist-rugs/python-rugs"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"
    - "org": ".org"

