dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: E2mn9Fhbil3HAgr3g0wb3Mxsb9tzHcWyItoj+L7lSDLNZTNU09o+vin87DTleUF6JS1yKwOXuC8Exd0JVY9YlTcNfmJpQsTq1xvMJIhSQfItssq58F3iXBkAFWxl+SEaIZBC2ErGIuo5rwoaDHfZpmv0fLlgXLIvVVH6yPGlYXdc79bfIetOJ117b/qA2A/mez8GpBGYGNbx+Gmh7FCAksfFU2VYs4vwHrdHLA8TRNnM290lXUnRgB0IE2YiexFBMsRN2zL+7d7uhr7O/18RIqC5+b7ni2wfw0m5Nx04McS5xn2ulLxg9j6frKH/biFqrUEhBTYRfDJ09n79JzK9oOuitYliRLlMdvWpfD5l1phML874QP9y3RKoPzoj1VcKzzN0G8iJczZhnaWiJIWsuUjvKEZm4UMX934xxAT6BAL/+Lkah5glmBnhiKQV6Xv8SC+LHYrSUcg33dhY8zP1PR6s0TW1YAV9J3yu85WRMq7SEP3pgVNZxbf9EWYkVl5qnP3RykY1Xd0Nn7EQJz7YQ1ldmqH4kmQua3cEAs5J8eKvVQ4/H6gKly8Qvp3UkgPCgV+wThBhuqUH9AVEcYY0o/L8mnWDeahs1yBXpCHl5TAJ4tXjTK2Fd9pS7KQ+MvCZzH9h4WTzpi99Kw9TsOexSx73Dc50751udwvEKA1gvO4=
  - secure: eKphWCt4PMagyO9yTPzBG/rhST2gzN0XWfklotDY+xFFaY5uXM79UuBwKmvOQnRzsq2QWXGc2vbFdxOG3POgh49EBPlE3HWRmoTHD/ZVCGgxXvFJSTXvB6gCN+SlA4qL3DO1sYFMTDJmMplH1ihBAwpDINDenPjZBggD2sTcSWRS1M814u7iRtu/MYgx3rFKAKnnYnVrbb07czMiXNDzQOI8uRkrESf1fxTGcsBfNbgrtXTSmNQXEpG+Qjlw4sVmgJGUB1twVfauEN1PnvVzFX38oLaIlsvpXFzbuVv9rq3FuRR3qGO2MrZzHnrdxSvKsNkTfBBADWrxUyCdS9qlJg5gg4Z0QyY7rTZ174/M4bubB3Dk9PVWJHgYsAQ2mKPgddg6wF6yDPweHKwOBlGhsmigl/KXFjpfZjaAkGBCujWKiMNwyDcZiuWJLyn5K8c1O3mU1G9Df+3fgiOgpS80RcoX7yMPp5MrzlCkUBuF9/uGj5BndvfXwcmVqBtK5cQQ7GDmDO0o94AxPy1A/ziof+0LVFP4QFTDTAD175GJzhwpc65b2L4mTm52CmXNdO0miZ7IDDYOJhd3gTwch7xzc3O1CsZ9/WN7uNaD6qlS1iogulV+M1Hd2ibXDAGoIWuKwSJxtPOfJSl4WjwhdY4rIdL6DZwZOhs5edKfCtNd69o=
  - secure: H7XwLRSXMFb1qZStn5rd6xgGyNjOzOoNHN4k/Y+Jpev1UARmf2DDy6MRqR8PMRiG+rscieI8p5iYWAB356by24XmH8zJ7JhlHMmK7IxNHSuaydjTwDciuI5xTF/F/vQOPGN+Dk/DsRFvRmyTbgvyJLkG5JrS76Zt0xPS8/spNHv8cCsvaTdzDLPEHRCsQUtLH5Zty0BQqehEbOx8hAS5R/tfVvIzxrpYzr1jVbV9cYhUBSzaspiqDLSyNe0/dHABhDIYeie1fhIwIrCqEPDwibQHpnw4rhDVRhaKiaAVie+fxjLDMFWrQa0GT/tkL6WcVHf6IkBjujdtVJYKSrRJI0p95PveclDjI9oGl+exHh1Yk8yGrHOkl08HMGCBH1iNCq4q/abfsbGaHmiz8y8TDPX0xwR+woxMAbgYdYsNAAgk0AHzehosSoscNXoyJNFScey2BXsnorHlCjiwxOYbe9OVggeRcv0/5A30YZ5kyZy0aRZRoltQMcIUiBRBcoI0+ha0MWGYk6c0mAIkYwenexz+g2vut+frL7rCJQncXpYyZGQnfgagbzqfB3Svm9j5BWuAwdC0N7QPCc9JjKqVNGNvk5GgKorjLS7U9mPWMPhMiEqDm+tHdkvxwSBP/nn948DA7IYlShJAClWHifhVBulNeXCZp6wT+pESM+Wlmdo=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
